FROM gcc:10.1.0
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev libjansson-dev libgmp-dev qt5-default qtbase5-dev qt5-qmake qtbase5-dev-tools libboost1.67-all-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
