FROM gcc:10.1.0
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev libjansson-dev libgmp-dev libboost1.67-all-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
